### ISSUE TITLE
Fix formatting on General Objectives page

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/Sampling-Decision-Assistant#10]
Chris, 

I'm not efficient at writing and formatting using these ionic elements. Could you take my filler on the objectives page and put it into a better format (whatever format you're creating for the other main sections - indicators, reporting-level, target-population etc)

**Comment by chrismclarke** [comment]
There's no point worrying too much about formatting as we don't really know what shape the content is coming in as. I've added proper linking structures for the survey questions and glossary, if you take a look at what's now there you can see the new markup I've created which is hopefully fairly intuitive:

`<survey-question-group *ngIf="sectionMeta.questions" [questions]="sectionMeta.questions" [questionNumber]=2 [showLabel]=false></survey-question-group>`

The new optional fields of 'questionNumber' and 'showLabel' are simply to display an individual question instead of the full group and whether to display the question label. In the case of the placeholder content you created this is set to false as you already have all of the direction required.

@dave-mills , feel free to close this thread once you have had time to take a quick look at the structure
