### ISSUE TITLE
Show side menu (or quick skip-back-to-home button) on most (all?) pages

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/Sampling-Decision-Assistant#12]
Can we have a menu icon on the step-by-step pages?

**Comment by chrismclarke** [comment]
I don't think this would be a good idea as once the user is in the step-by-step process we shouldn't be encouraging them to leave. Every page has a back button to take back to the main overview page, and other sections that might be of relevance (e.g. glossary for terms) should be dynamically linked into the content itself instead of expecting the user to manually navigate back and forth. Ionic provides a modal controller to do this when you want to temporarily push a page on to the top of the nav stack (essentially a popup).

Did you have any other reasons for doing so?
